os:
  editPreset: "nvim"
  openLink: open "$(echo "{{link}}" | sed 's/%2F/\//g')"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --side-by-side
gui:
  showIcons: true
  changed_files_width: 20
  enlargedSideViewLocation: top
