---
os:
  editPreset: nvim
  openLink: open "$(echo "{{link}}" | sed 's/%2F/\//g')"
  edit: '[ -z "$NVIM" ] && (nvim -- {{filename}}) || (nvim --server "$NVIM" --remote-send
    "q" && nvim --server "$NVIM" --remote {{filename}})'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --side-by-side
gui:
  showIcons: true
  changed_files_width: 20
  enlargedSideViewLocation: top
  showCommandLog: false
  authorColors:
    '*': '#99c792'
  theme:
    activeBorderColor: ['#ffcb6b']
    # Border color of non-focused windows
    inactiveBorderColor: ['#f1e4c2']
    # Border color of focused window when searching in that window
    # doesn't work in snacks lazygit
    searchingActiveBorderColor: ['#e396a4', bold]
    # Color of keybindings help text in the bottom line
    optionsTextColor: ['#82aaff']
    selectedLineBgColor: ['#393939']

    # Foreground color of copied commit
    cherryPickedCommitFgColor: ['#ffffff']
    # Background color of copied commit
    cherryPickedCommitBgColor: ['#e89a5e']

    # Foreground color of marked base commit (for rebase)
    markedBaseCommitFgColor:
      - blue

    # Background color of marked base commit (for rebase)
    markedBaseCommitBgColor:
      - yellow

    # Color for file with unstaged changes
    unstagedChangesColor: ['#eb7a73']
    # Default text color
    defaultFgColor: ['#f1e4c2']
