---
os:
  editPreset: nvim
  openLink: open "$(echo "{{link}}" | sed 's/%2F/\//g')"
  edit: '[ -z "$NVIM" ] && (nvim -- {{filename}}) || (nvim --server "$NVIM" --remote-send
    "q" && nvim --server "$NVIM" --remote {{filename}})'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --side-by-side
gui:
  showIcons: true
  changed_files_width: 20
  enlargedSideViewLocation: top
  showCommandLog: false
  authorColors:
    '*': '#99c792'
  theme:
    activeBorderColor: ['#ffcb6b']
    inactiveBorderColor: ['#f1e4c2']
    searchingActiveBorderColor: ['#e396a4', bold]
    optionsTextColor: ['#82aaff']
    selectedLineBgColor: ['#393939']
    cherryPickedCommitFgColor: ['#FFFFFF']
    cherryPickedCommitBgColor: ['#e89a5e']
    markedBaseCommitFgColor: ['#82aaff']
    markedBaseCommitBgColor: ['#ffcb6b']
    unstagedChangesColor: ['#eb7a73']
    defaultFgColor: ['#e5d5b1']
