format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$line_break\
$character"""

palette = 'onedark'

[directory]
style = 'bold fg:yellow'
format = '[$path ]($style)'
truncate_to_repo = false
truncation_length = 5
truncation_symbol = '.../'

[character]
success_symbol = '[➜](bold white) '
error_symbol = '[✗](bold red) '

[git_branch]
style = 'fg:green'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = 'fg:green'
format = '([$ahead_behind]($style) )'
behind = '[⇣$count](yellow)'
ahead = '[⇡$count](dark_green)'
diverged = '[⇡$ahead_count](dark_green)[⇣$behind_count](yellow)'

[nodejs]
symbol = ' '
style = 'fg:dark_green'
format = '[via](white) [$symbol($version(-$name) )]($style)'

[palettes.nord]
dark_blue = '#5E81AC'
blue = '#81A1C1'
teal = '#88C0D0'
red = '#ed8796'
orange = '#D08770'
green = '#a6da95'
dark_green='#98c379'
yellow = '#eed49f'
purple = '#B48EAD'
gray = '#434C5E'
black = '#2E3440'
white='#D8DEE9'

[palettes.onedark]
red = '#eb7a73'
green = '#7cb66a'
dark_green = '#99c792'
yellow = '#ffcb6b'
white = '#D8DEE9'
